signup_enabled = true
addr = 8090
domain = "http://example.com"
page_size = 5
smms_fileserver = "https://sm.ms/api/upload"
fileserver = "smms" # or qiniu
notify_emails = ""
session_secret = "wblog"
public = "static"

[database]
dialect = "sqlite3" # sqlite3 or mysql
dsn = "wblog.db?_loc=Asia/Shanghai" # "root:mysql@/wblog?charset=utf8&parseTime=True&loc=Asia/Shanghai"

[fileservers]
    [fileservers.qiniu]
    [fileservers.smms]

[[navigators]]
title = "AboutMe"
url = "/page/6"

[[navigators]]
title = "Resume"
url = "/page/7"

[github]
clientid = ""
clientsecret = ""
authurl = "https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s"
redirecturl = "http://localhost:8090/oauth2callback"
tokenurl = "https://github.com/login/oauth/access_token"
scope = ""

[smtp]
username = "your email account"
password = "your password"
host = "smtp.163.com:25"

[backup]
enabled = false
backup_key = ""
qiniu_accesskey = ""
qiniu_secretkey = ""
qiniu_fileserver = ""
qiniu_bucket = ""