addr = 8090
signup_enabled = true
domain = "https://example.com"
file_server = "smms" # smms or qiniu
notify_emails = ""
page_size = 5
session_secret = "wblog"
public = "static"

[database]
dialect = "sqlite3"
dsn = "wblog.db?_loc=Asia/Shanghai"
#dialect = "mysql"
#dsn = "root:mysql@/wblog?charset=utf8&parseTime=True&loc=Asia/Shanghai"

[seo]
description = ""
author = ""

[qiniu]
accesskey = ""
secretkey = ""
fileserver = ""
bucket = ""

[smms]
fileserver = "https://sm.ms/api/upload"

[github]
clientid = ""
clientsecret = ""
redirecturl = "https://example.com/oauth2callback"
authurl = "https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s"
tokenurl = "https://github.com/login/oauth/access_token"
scope = ""

[smtp]
username = "[your email account]"
password = "[your password]"
host = "smtp.163.com:25"

[[navigators]]
title = "Posts"
url = "/index"

[[navigators]]
title = "AboutMe"
url = "/page/6"

[[navigators]]
title = "RSS"
url = "/rss"

[[navigators]]
title = "Subscribe"
url = "/subscribe"

# backup only support sqlite dialect
[backup]
enabled = false
backup_key = ""